# docker-compose.yml for travis ci testing
services:
  emr:
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile 
    ports:
      - "3000:3000"
    volumes:
    - ./src:/app/src:ro
    - ./static:/app/static:ro
    - ./templates:/app/templates:ro
    - ./Cargo.toml:/app/Cargo.toml:ro
    - ./askama.toml:/app/askama.toml:ro
    - ./dev.toml:/app/app.toml:ro
    - ./migrations:/app/migrations:ro
    environment:
      DATABASE_URL: postgres://root:password@postgres:5432/db
    depends_on:
    - postgres
  postgres:
    image: postgres:latest  # Use the official PostgreSQL image
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: db
    volumes:
      - pg_db:/var/lib/postgresql/data # Mount a volume for persistence
volumes:
  pg_db: {}

